### ISSUE TITLE
Failed to get a signed key from the CA: timed out while waiting for a response from the CA

### ISSUE THREAD

**Issue by doodlemania2** [keybase/bot-sshca#33]
In the subteam, I'm seeing these items come in quick succession:

AckRequest--<user>

But kssh-windows gives the above error. Any options for troubleshooting?

**Comment by doodlemania2** [comment]
Thanks so much! I did a git pull and got the updates. removed the old container and did a new make serve with no change. Am doing a docker logs -f to watch for activity. Any debug mode flag or anything I can try?

**Comment by ddworken** [comment]
There isn't a built in debug flag (since this has always worked for us, so just haven't built it yet) but I can definitely get started on making one. As a first guess, what is the output of (feel free to censor any secrets in the output): 

```
cd docker/
make build
source env.sh && docker run -e FORCE_WRITE=$(FORCE_WRITE) -e KEYBASE_USERNAME -e KEYBASE_PAPERKEY -e TEAMS -v $(CURDIR)/example-keybaseca-volume:/mnt:rw ca:latest env
```

I just want to see whether the environment variables are properly getting forwarded to the docker container. If so, then it must be some other issue so I'll work on a debug flag with much more detailed logging.

**Comment by doodlemania2** [comment]
Here you go!
derek@stuff:~/bot-sshca/docker$ source env.sh && docker run -e FORCE_WRITE=$(FORCE_WRITE) -e KEYBASE_USERNAME -e KEYBASE_PAPERKEY -e TEAMS -v $(CURDIR)/example-keybaseca-volume:/mnt:rw ca:latest env
FORCE_WRITE: command not found
CURDIR: command not found
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=043e7ee79db0
TEAMS=derekteam.pi,derekteam.azure,derekteam.google,derekteam.root
FORCE_WRITE=
KEYBASE_USERNAME=<this is correct>
KEYBASE_PAPERKEY=<this is correct>
HOME=/root

**Comment by ddworken** [comment]
Ah, so something weird is going on with your environment variable passing! It seems as though the `KEYBASE_USERNAME` and `KEYBASE_PAPERKEY` environment variables are not getting passed through to the container. In your copy and pasted env file I see the line:

```
export KEYBASE_PAPERKEY="super secret key
```

Note the lack of a closing quotation mark. Is that true in the uncensored env file also? If so, I think that is likely the issue. 

Otherwise, what shell and OS are you using? And what is the output of:

```
cd docker/
source env.sh && env
```

**Comment by Johannestegner** [comment]
Would it be possible to consider a `.env` file instead of the env.sh file? Docker accepts env files with `--env-file .env` and will import all vars in one of those as env variables.

**Comment by ddworken** [comment]
@johannestegner Yes! That is on my to-do list for this project and I think is necessary to do long term. I just hadn't realized that was a feature so didn't do it that way from the beginning.

**Comment by Johannestegner** [comment]
@ddworken is there any other dependencies on the environment variables/files than the actual docker images? I saw that there where some in the tests, but not sure if the "real one" is required for that?

Else I could take a look at it tomorrow, if you wish ;)

**Comment by doodlemania2** [comment]
So here's env.sh slightly smudged to protect the innocent:
![image](https://user-images.githubusercontent.com/5252217/64041026-fa96ee00-cb23-11e9-9086-e2f17572d357.png)

and my env:

:~/bot-sshca/docker$ source env.sh && env
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=<nameste>
LESSCLOSE=/usr/bin/lesspipe %s %s
LANG=C.UTF-8
DISPLAY=localhost:12.0
OLDPWD=/home/derek/bot-sshca
XDG_SESSION_ID=170275
USER=derek
KEYBASE_USERNAME=<correct>
PWD=/home/derek/bot-sshca/docker
HOME=/home/derek
SSH_CLIENT=<hi there hehee>
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
KEYBASE_PAPERKEY=<same as pic above>
SSH_TTY=/dev/pts/2
MAIL=/var/mail/derek
TERM=xterm
SHELL=/bin/bash
SHLVL=1
LOGNAME=derek
XDG_RUNTIME_DIR=/run/user/1000
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
TEAMS=<same as pic>
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/env


I'm Ubuntu 18.LTS

**Comment by Johannestegner** [comment]
It looks like the env.sh file does not actually set the env variables in the shell...  
Now, I'm not a part of the team here, but thought I'd throw in a helping hand just to see if I could help a bit!

Could you try the following:

Move the env.sh file content over to a file that you name `.env`, make it look like the following:

```
TEAMS=teamname.ssh.staging,teamname.ssh.production,...
KEYBASE_USERNAME=username_of_ca_bot
KEYBASE_PAPERKEY=paper key for the ca bot
```

Then try run:   
`docker run -d --restart unless-stopped --env-file ./.env -v $(CURDIR)/example-keybaseca-volume:/mnt:rw ca:latest docker/entrypoint-server.sh`

By doing this, you tell docker to use the `.env` file and populate the containers environment variables with the fields in the file.

**Comment by ddworken** [comment]
Thanks for the suggestion @Johannestegner. I just spent a bit of time trying to implement that and the difficulty with the env-file solution comes from using `sudo` inside of the container to drop privileges. But, I think I have a better solution. 

@doodlemania2 Can you `git pull && git checkout david/docker-env-file` ([this](https://github.com/keybase/bot-sshca/tree/david/docker-env-file) branch) and try again? Now all of the environment variables are only set inside of the container once running as the current user. I also added some additional debugging so it will run `env` from the `keybase` user which is used to run the bot. 

I still don't quite get why it is that you are running into this issue (since it works perfectly when I test it on 18.04) but I am determined to figure it out. :) So thanks for all the patience!

**Comment by doodlemania2** [comment]
No worries at all - I sure hope I'm not just doing something stupid (likley). Here's the make generate after switching to your other branch:

docker run -e FORCE_WRITE=false -v /home/derek/bot-sshca/docker/example-keybaseca-volume:/mnt:rw ca:latest docker/entrypoint-generate.sh
SUDO_GID=0
HOSTNAME=a6e6907520b3
USERNAME=keybase
SUDO_COMMAND=/bin/bash -c bash
USER=keybase
KEYBASE_USERNAME=<my keybase username>
PWD=/home/keybase
HOME=/home/keybase
SUDO_USER=root
KEYBASE_PAPERKEY=<this is accurate, not quotes>
FORCE_WRITE=false
SUDO_UID=0
MAIL=/var/mail/keybase
SHELL=/bin/bash
TERM=unknown
SHLVL=2
LOGNAME=keybase
PATH=/home/keybase/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
TEAMS=<comma separated lists without spaces, is accurate>
_=/usr/bin/env
Launching keybase service...
Starting the redirector...
Starting KBFS...
run_keybase: Success!
KBFS failed to FUSE mount at /home/keybase/.config/keybase/kbfs: fusermount: exit status 1
Generated new public key: 
<nice long key>
keybase@a6e6907520b3
[2019-09-03 15:36:30.268552072 +0000 UTC m=+0.032720461] Wrote new SSH CA key to /mnt/keybase-ca-key

Run these commands on each server that you wish to use with the CA chatbot

useradd developer && mkdir -p /home/developer && chown developer:developer /home/developer  # The user that will be used for non-root logins
<nice long key>
keybase@a6e6907520b3" > /etc/ssh/ca.pub
echo "TrustedUserCAKeys /etc/ssh/ca.pub" >> /etc/ssh/sshd_config
echo "AuthorizedPrincipalsFile /etc/ssh/auth_principals/%u" >> /etc/ssh/sshd_config
chmod g-w /etc   # On some distributions /etc is group writable which will cause SSH to refuse to run
service ssh restart

See the README for information on how to define which teams are allowed to access which servers

.....................
When I run kssh from windows, still getting: Failed to get a signed key from the CA: timed out while waiting for a response from the CA

Keybase client (windows) shows AckRequest--<myusername>
.......................

docker logs -f on the server running the bot:
SUDO_GID=0
HOSTNAME=b4bc216355f8
USERNAME=keybase
SUDO_COMMAND=/bin/bash -c bash
USER=keybase
KEYBASE_USERNAME=<my username>
PWD=/home/keybase
HOME=/home/keybase
SUDO_USER=root
KEYBASE_PAPERKEY=<paper key, no quotes, is accurate>
SUDO_UID=0
MAIL=/var/mail/keybase
SHELL=/bin/bash
TERM=unknown
SHLVL=2
LOGNAME=keybase
PATH=/home/keybase/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
TEAMS=<comma separated list, no spaces, is accurate>
_=/usr/bin/env
Launching keybase service...
Starting the redirector...
Starting KBFS...
run_keybase: Success!
KBFS failed to FUSE mount at /home/keybase/.config/keybase/kbfs: fusermount: exit status 1
Started CA bot...
(not seeing anything logged here when I run kssh from my windows box)
................................

Just a reminder - the windows box I'm running kssh from is on one side of the planet and the CA bot is on the other side, in another cloud, with all ports closed.

**Comment by ddworken** [comment]
Resolving this now that we got this issue resolved and fixes merged to master.
