### ISSUE TITLE
Integration test should not run prune.

### ISSUE THREAD

**Issue by Johannestegner** [keybase/bot-sshca#39]
As of right now, when running the `integrationTests.sh` file, the `reset_docker` function is called. This is not great on a local development machine where docker is used!
_(I just lost all my containers, networks and volumes that I had running locally, that includes a bunch of locally seeded databases!)._

I'm guessing that all that is intended to be deleted is the stuff that is created within the tests? In that case, as it uses docker compose already, it might be best to just run `docker-compose down` to remove all the containers, networks and volumes created by `docker-compose up`. Making the thing a tad bit more isolated to just the test case.

**Comment by ddworken** [comment]
I'm sorry about that! Created a PR #42 to switch to using `docker-compose down` with some additional flags to remove the images/volumes associated with it. I had not thought about the case of local non-attached volumes and thought that it would be a safe command to run.

**Comment by Johannestegner** [comment]
No problems, most are stateless so it's fine :)
Nice speed on fix :)
