### ISSUE TITLE
Updating env.sh with additional teams

### ISSUE THREAD

**Issue by schlos** [keybase/bot-sshca#62]
I have installed bot-sshca by following Getting started steps.

When I update env.sh with additional teams, do I need to run again make?
If yes, do I need to stop previous/existing docker?
What is exact procedure?

Thanks!

**Comment by ddworken** [comment]
Thanks for the feedback! I just opened a PR to add docs on this and make it slightly easier. Until that change is merged, the procedure is just stopping and restarting the docker container (note that you do not need to regenerate keys). 

```
docker kill `docker ps -q --filter ancestor=ca`
make serve
````

In the future, it will simply be `make restart`
