### ISSUE TITLE
Feature Request: option to auto explode AckRequests and answers

### ISSUE THREAD

**Issue by krezreb** [keybase/bot-sshca#85]
While I understand the point of having AckRequests and Acks in chat channels, in certain cases it might be nice to have them auto [explode](https://keybase.io/blog/keybase-exploding-messages).  For example, if I need to track which users signed in, the bot's response with the certificate is enough.  Once the bot has given this cert, I really don't care about the Ack messages.

It would be nice for these Ack messages to auto explode.  The default could, for example, be 5minutes, and of course be configurable

**Comment by joshblum** [comment]
@krezreb you can set an exploding retention policy on the conversation and the client will respect the policy and apply the default. @mmou we can likely close https://github.com/keybase/go-keybase-chat-bot/issues/68 as a result

**Comment by mmou** [comment]
Setting the conversation retention policy to is a decent alternative, but perhaps the intention of this request is to be able to retain the Signature_Request and Signature_Response messages, and only explode the AckRequest and Ack messages.

If you set the policy to explode all messages, you can still audit logins by looking at your SSH CA logs at `LOG_LOCATION`.

**Comment by mmou** [comment]
deprioritizing until there is a reason why the above suggestion doesn't work
