### ISSUE TITLE
Fails to start up on Rpi

### ISSUE THREAD

**Issue by blaggacao** [keybase/bot-sshca#91]
On Raspberry Pi 3B V1.2, starting the `keybase service` consistently fails with the following log output:
```shell
Failed to write the client config: failed to start Keybase chat: unable to run Keybase command
```

I traced the last part down to this line:
https://github.com/keybase/go-keybase-chat-bot/blob/81b8e08b23b9f3e1a602cbfabb457c308604578f/kbchat/kbchat.go#L232

Which was recently added through https://github.com/keybase/go-keybase-chat-bot/pull/64 (16 days before this report). The used build is from today.

What to do? /cc @joshblum

**Comment by mmou** [comment]
closing this with merging of https://github.com/keybase/bot-sshca/commit/8ea43a4aebe513324b791500fa9462e33e52e0b5, but let us know if you are still having problems.
